/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-07-22 10:11:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.flows.flows_002dshared;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/Sunil%20kumar%20pandey/Desktop/FashionWheel%20Niit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FashionWheel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/views/Shared/footer.jsp", Long.valueOf(1532253117208L));
    _jspx_dependants.put("/views/flows/flows-shared/./shared/flow-footer.jsp", Long.valueOf(1528136729908L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.14.RELEASE.jar", Long.valueOf(1519487349631L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1515920760450L));
    _jspx_dependants.put("jar:file:/C:/Users/Sunil%20kumar%20pandey/Desktop/FashionWheel%20Niit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FashionWheel/WEB-INF/lib/spring-webmvc-4.3.14.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1516677330000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Readable Theme -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap-readable-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myapp.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Online Shopping - FlowException</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t            <div class=\"navbar-header\">\r\n");
      out.write("\t                <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">Home</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h1>Please contact your administrator!</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<blockquote style=\"word-wrap:break-word\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flowExecutionException}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</blockquote>\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<blockquote style=\"word-wrap:break-word\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootCauseException}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</blockquote>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("<!-- Footer -->\r\n");
      out.write("\t\t");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- ICON NEEDS FONT AWESOME FOR CHEVRON UP ICON -->\r\n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Css For Scroll top -->\r\n");
      out.write("<style>\r\n");
      out.write("#return-to-top {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    bottom: 20px;\r\n");
      out.write("    right: 20px;\r\n");
      out.write("    background: rgb(0, 0, 0);\r\n");
      out.write("    background: rgba(0, 0, 0, 0.7);\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    -webkit-border-radius: 35px;\r\n");
      out.write("    -moz-border-radius: 35px;\r\n");
      out.write("    border-radius: 35px;\r\n");
      out.write("    display: none;\r\n");
      out.write("    -webkit-transition: all 0.3s linear;\r\n");
      out.write("    -moz-transition: all 0.3s ease;\r\n");
      out.write("    -ms-transition: all 0.3s ease;\r\n");
      out.write("    -o-transition: all 0.3s ease;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("#return-to-top i {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left: 16px;\r\n");
      out.write("    top: 13px;\r\n");
      out.write("    font-size: 19px;\r\n");
      out.write("    -webkit-transition: all 0.3s ease;\r\n");
      out.write("    -moz-transition: all 0.3s ease;\r\n");
      out.write("    -ms-transition: all 0.3s ease;\r\n");
      out.write("    -o-transition: all 0.3s ease;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("#return-to-top:hover {\r\n");
      out.write("    background: rgba(0, 0, 0, 0.9);\r\n");
      out.write("}\r\n");
      out.write("#return-to-top:hover i {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<hr>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"footer\" >\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"col-md-3 footer-grids fgd1\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>1234k Avenue, 4th block,</li>\r\n");
      out.write("\t\t\t<li>New York City.</li>\r\n");
      out.write("\t\t\t<li><a href=\"mailto:info@example.com\">info@example.com</a></li>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-3 footer-grids fgd3\">\r\n");
      out.write("\t\t\t<h4>Products</h4> \r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"jewellery.html\">Jewellery</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"cosmetics.html\">Cosmetics</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"Shoes.html\">Shoes</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"deos.html\">Deos</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-3 footer-grids fgd4\">\r\n");
      out.write("\t\t\t<h4>My Account</h4> \r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i>&nbsp;&nbsp;&nbsp; Login</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\"> <i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>&nbsp;&nbsp;&nbsp;Register</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/show\"><i class=\"fa fa-opencart\" aria-hidden=\"true\"></i>&nbsp;&nbsp;&nbsp;My Cart</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"error404\"> <i class=\"fa fa-user\" aria-hidden=\"true\"></i>&nbsp;&nbsp;&nbsp; Payments</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-3 footer-grids fgd2\">\r\n");
      out.write("\t\t<h4>Find Us</h4><p>\r\n");
      out.write("                           <div class=\"myframegmap\"> \r\n");
      out.write("                           <iframe width=\"259\" height=\"200\" id=\"gmap_canvas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://maps.google.com/maps?q=new delhi&t=&z=13&ie=UTF8&iwloc=&output=embed\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tframeborder=\"0\" scrolling=\"yes\" marginheight=\"0\" marginwidth=\"0\"></iframe>\r\n");
      out.write("                    </div></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t<p class=\"copy-right\"><strong>Copyright © Fashion Wheel 2018 <br>All right reserved.</strong>| Design by <a href=\"http://w3layouts.com\"> Fashion Wheel</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- start-smoth-scrolling -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- start-smoth-scrolling -->\r\n");
      out.write("\r\n");
      out.write("<!-- here stars scrolling icon -->\r\n");
      out.write("\t<!-- <script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\r\n");
      out.write("\t\t\t$().UItoTop({\r\n");
      out.write("\t\t\t\teasingType: 'easeOutQuart'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script> -->\r\n");
      out.write("\t<!-- //here ends scrolling icon -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Return to Top -->\r\n");
      out.write("<a href=\"javascript:\" id=\"return-to-top\" title=\"Click to return on the top page\" data-toggle=\"tooltip\" data-placement=\"left\"><i class=\"icon-chevron-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//===== Scroll to Top ==== \r\n");
      out.write("$(window).scroll(function() {\r\n");
      out.write("    if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px\r\n");
      out.write("        $('#return-to-top').fadeIn(200);    // Fade in the arrow\r\n");
      out.write("    } else {\r\n");
      out.write("        $('#return-to-top').fadeOut(200);   // Else fade out the arrow\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("$('#return-to-top').click(function() {      // When arrow is clicked\r\n");
      out.write("    $('body,html').animate({\r\n");
      out.write("        scrollTop : 0                       // Scroll to top of body\r\n");
      out.write("    }, 500);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"footer\">\r\n");
      out.write("\t<div class=\"footer1\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t  <h2>About Us</h2>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t<h2>Home</h2>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-home\">&nbsp;</i>      <a href=\"#\"> Home</a><br>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-user-o\">&nbsp;</i>    <a href=\"#\"> About Us</a><br>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-map-marker\">&nbsp;</i>   <a href=\"#\"> Contact Us</a><br>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-briefcase\">&nbsp;</i> <a href=\"#\"> Services</a><br>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-question-circle\"></i><a href=\"#\"> Term & Conditions</a><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-3 \">\r\n");
      out.write("\t\t\t<h2>Contact Us</h2>\r\n");
      out.write("\t\t\t<p >\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-phone\"></i>    <a href=\"tel:0123456789\"> +0123456789</a><br>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-envelope\"></i>    <a href=\"mailto:abc@abc.com\"> abc@abc.com</a><br>\r\n");
      out.write("\t\t\t\t<i id=\"footer-item\" class=\"fa fa-map-marker\"></i>     New-Delhi Capital, India\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t  <h2>Find Us</h2><p>\r\n");
      out.write("                           <div class=\"myframegmap\"> \r\n");
      out.write("                           <iframe width=\"259\" height=\"200\" id=\"gmap_canvas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://maps.google.com/maps?q=new delhi&t=&z=13&ie=UTF8&iwloc=&output=embed\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tframeborder=\"0\" scrolling=\"yes\" marginheight=\"0\" marginwidth=\"0\"></iframe>\r\n");
      out.write("                    </div></p>\r\n");
      out.write("                    <br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div></div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class =\"container\" id=\"social\">\r\n");
      out.write("\t\t\t\t<h3>Follow us on</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"social-top\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i><span></span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i><span></span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon pinterest\"><i class=\"fa fa-pinterest-p\" aria-hidden=\"true\"></i><span></span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon youtube-play\"><i class=\"fa fa-youtube-play\" aria-hidden=\"true\"></i><span></span></a></li>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" style=\"background-color:white;\">\r\n");
      out.write("\r\n");
      out.write(" <hr style=\"margin-bottom:0px; margin-top:30px; padding:0px;\">\r\n");
      out.write("        <div class=\"row \" id=\"sub-two\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"vertical-line text-center\">\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-map-marker\" id=\"Service1\"></span>\r\n");
      out.write("                    <h4>TRACK YOUR ORDER</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"vertical-line text-center\">\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-refresh\" id=\"Service1\"></span>\r\n");
      out.write("                    <h4>FREE & EASY RETURNS</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div style=\"margin:8px;\" class=\"vertical-line text-center\">\r\n");
      out.write("                    <span class=\"glyphicon glyphicon-remove-circle\" id=\"Service1\"></span>\r\n");
      out.write("                    <h4 style=\"color:#6d6c6c;\">ONLINE CANCELLATIONS</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"margin-bottom:15px; margin-top:0px; padding:0px;\">\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer2\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"clear30\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 text-center\"><p><strong>Copyright © Fashion Wheel 2018 <br>All right reserved.</strong></p></div>\r\n");
      out.write("\t\t\t<div class=\"clear30\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("    <div class=\"container footer\">\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        Footer\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <p>Copyright &copy; Fashion Wheel 2018 </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t<div>\r\n");
      out.write("\t\t<footer class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">Fashion Wheel</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"para\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\tadipiscing elit. Proin suscipit, libero a molestie consectetur,\r\n");
      out.write("\t\t\t\t\t\t\tsapien elit lacinia mi.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"social-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social\"><i class=\"fa fa-facebook\" id=\"fb\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social\"><i class=\"fa fa-twitter\" id=\"tw\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social\"><i class=\"fa fa-instagram\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"insta\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social\"><i class=\"fa fa-youtube-play\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"you\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social\"><i class=\"fa fa-google\" id=\"goo\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-hidden=\"true\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">My Account</h4>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"acount-icon\"> <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-heart\" aria-hidden=\"true\"></i> Wish List</a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\"><i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tCart</a> <a href=\"#\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\tProfile</a> <a href=\"#\"><i class=\"fa fa-globe\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> Language</a>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">Category</h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">men</a> <a href=\"#\">women</a> <a href=\"#\">boy</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">girl</a> <a href=\"#\">bag</a> <a href=\"#\">teshart</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">top</a> <a href=\"#\">shos</a> <a href=\"#\">glass</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">kit</a> <a href=\"#\">baby dress</a> <a href=\"#\">kurti</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">Useful link</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footer-ul\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"product\">Product</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"title\">Direction</h4>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe width=\"259\" height=\"200\" id=\"gmap_canvas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://maps.google.com/maps?q=new delhi&t=&z=13&ie=UTF8&iwloc=&output=embed\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tframeborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row text-center\">© 2018. Made by Rksensational.</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div> -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- DataTable Plugin -->\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery.dataTables.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- DataTable Bootstrap Script -->\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dataTables.bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  Bootbox Script -->\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootbox.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Custom js -->\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/myhome.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /views/flows/flows-shared/error.jsp(6,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("css");
      // /views/flows/flows-shared/error.jsp(6,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/resources/css");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /views/flows/flows-shared/error.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextRoot");
      // /views/flows/flows-shared/error.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/flows/flows-shared/error.jsp(8,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
