/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-07-16 17:04:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mquickview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\" class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicon.ico\"/>\r\n");
      out.write("<meta name=\"application-name\" content=\"Fashion Wheel\"/>\r\n");
      out.write("<meta name=\"msapplication-TileColor\" content=\"#7a7a7a\"/>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Merienda|Raleway\" rel=\"stylesheet\">\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!--MDB core css-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reset.css\">\r\n");
      out.write("<!-- CSS reset -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/quick.css\">\r\n");
      out.write("<!-- Resource style -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/modernizr.js\"></script>\r\n");
      out.write("<!-- Modernizr -->\r\n");
      out.write("\r\n");
      out.write("<title>Product Quick View | CodyHouse</title>\r\n");
      out.write("\r\n");
      out.write("<!-- BOOTSTRAP RESPONSIVE -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<!-- Navigation -->\r\n");
      out.write("\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t<a class=\"btn  btn-info\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">Home</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h1 style = \"font-family: 'Merienda', cursive; color:black; font-size:2em;\">Men Fashion Store</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=container>\r\n");
      out.write("\t<img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/menban.jpg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"container cd-items\">\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRD6F40930D69.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRD6F40930D69.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRD6F40930D69.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRD6F40930D69.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"cd-item\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\talt=\"Item Preview\"> <a href=\"#0\" class=\"cd-trigger\">Quick\r\n");
      out.write("\t\t\t\tView</a></li>\r\n");
      out.write("\t\t<!-- cd-item -->\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<!-- cd-items -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"cd-quick-view\">\r\n");
      out.write("\t\t<div class=\"cd-slider-wrapper\">\r\n");
      out.write("\t\t\t<ul class=\"cd-slider\">\r\n");
      out.write("\t\t\t\t<li class=\"selected\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRDCB7EC773D0.jpeg\"\r\n");
      out.write("\t\t\t\t\talt=\"Product 1\"></li>\r\n");
      out.write("\t\t\t\t<li><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRD6F40930D69.jpeg\"\r\n");
      out.write("\t\t\t\t\talt=\"Product 2\"></li>\r\n");
      out.write("\t\t\t\t<li><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/PRD73D8B3B7AB.jpeg\"\r\n");
      out.write("\t\t\t\t\talt=\"Product 3\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- cd-slider -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"cd-slider-navigation\">\r\n");
      out.write("\t\t\t\t<li><a class=\"cd-next\" href=\"#0\">Prev</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"cd-prev\" href=\"#0\">Next</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- cd-slider-navigation -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- cd-slider-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"cd-item-info\">\r\n");
      out.write("\t\t\t<h2>Produt Title</h2>\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\tOfficia, omnis illo iste ratione. Numquam eveniet quo, ullam itaque\r\n");
      out.write("\t\t\t\texpedita impedit. Eveniet, asperiores amet iste repellendus\r\n");
      out.write("\t\t\t\tsimilique reiciendis, maxime laborum praesentium.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"cd-item-action\">\r\n");
      out.write("\t\t\t\t<li><form\r\n");
      out.write("\t\t\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/add/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\"\r\n");
      out.write("\t\t\t\t\t\tmethod=\"get\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"add-to-cart\">Add to cart</button>\r\n");
      out.write("\t\t\t\t\t</form></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#0\">Learn more</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- cd-item-action -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- cd-item-info -->\r\n");
      out.write("\t\t<a href=\"#0\" class=\"cd-close\">Close</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- cd-quick-view -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/velocity.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\t<!-- Resource jQuery -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
